# Risk Management Configuration
max_position_size: 0.1  # 10% of portfolio
max_daily_loss: 500.0   # $500
stop_loss_pct: 0.02     # 2%
take_profit_pct: 0.04   # 4%
use_kelly_criterion: true
kelly_fraction: 0.25
