name: Phase IV Smoke CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phase4-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements.txt || true

      - name: Run Phase IV QA smoke
        run: |
          chmod +x scripts/run_phase4_qa.sh || true
          ./scripts/run_phase4_qa.sh --smoke
        continue-on-error: false

      - name: Upload artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase4-qa-artifacts
          path: artifacts/phase4_qa || artifacts || .

  phase4-robust:
    runs-on: ubuntu-latest
    needs: phase4-smoke
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt || true
      - name: Run short robustness (manual dispatch only)
        run: |
          ./scripts/run_phase4_qa.sh --robust
