name: replay-test
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          python -m pip install ruff
          ruff check .
      - name: Unit tests
        run: |
          pytest -q
      - name: Backtest Smoke (if cleaned CSV exists)
        run: |
          if [ -f data/cleaned/BTCUSD_1min.cleaned.csv ]; then \
            python scripts/run_backtest.py --config configs/trade_logic.yaml ; \
          else \
            echo "Skipping smoke: cleaned CSV missing"; \
          fi
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backtest-artifacts
          path: artifacts/**
